### ISSUE TITLE
Uncaught TypeError: manager.on is not a function

### ISSUE THREAD

**Issue by bingoyesbingoyes** [guansss/pixi-live2d-display#111]
![code](https://github.com/guansss/pixi-live2d-display/assets/49268613/b0e15729-eb20-46dd-8ce2-609834dbed08)
Hello! When I tried to run the code above, it reported errors below! I have checked for days, and I really need help:(
![error](https://github.com/guansss/pixi-live2d-display/assets/49268613/c7f9b796-a49e-4204-bff5-b4e3586d3752)

**Comment by guansss** [comment]
> **PixiJS Deprecation Warning:**
...
Deprecated since v7.0.0

You seem to be using an unsupported version. v7 and above is not yet supported.

**Comment by bingoyesbingoyes** [comment]
> 

tks, but honestly I wonder how to fix it. I have tried to use the older vision (yarn add pixi.js@6.9), and it reported the same error.

**Comment by bingoyesbingoyes** [comment]
![same](https://github.com/guansss/pixi-live2d-display/assets/49268613/046b1d68-342f-4a27-af53-ba484657e9a7)
and during searching for solvement. I have found (in this [link](https://blog.csdn.net/qq_47917308/article/details/116133349) ) others work with the similar problem, but he works.

**Comment by guansss** [comment]
There is no `pixi.js@6.9`, the latest 6.x version is `6.5.10`.

> with the similar problem

They *look* similar because they are both deprecation warnings... They are not similar in any other way.

**Comment by bingoyesbingoyes** [comment]
> There is no `pixi.js@6.9`, the latest 6.x version is `6.5.10`.
> 
> > with the similar problem
> 
> They _look_ similar because they are both deprecation warnings... They are not similar in any other way.

sorry I made a mistake, I do use 6.5.10
![Screenshot 2023-08-28 150023](https://github.com/guansss/pixi-live2d-display/assets/49268613/23914ede-9757-4377-ba27-8befda4212f9)

**Comment by bingoyesbingoyes** [comment]
and I woner maybe this warning is not the wrong point?

**Comment by guansss** [comment]
The warning is just a proof of the use of unsupported version and is not necessarily the root cause.

I just tested 6.5.10 and had no issue. Could you provide a minimal reproduction please?

**Comment by bingoyesbingoyes** [comment]
> The warning is just a proof of the use of unsupported version and is not necessarily the root cause.
> 
> I just tested 6.5.10 and had no issue. Could you provide a minimal reproduction please?

Yes! All my project and code is [here](https://github.com/bingoyesbingoyes/EverCraft/blob/master/src/pages/Test.vue). I'm trying to add a live2d model in my quasar project. I have just started, and it's not big.

**Comment by guansss** [comment]
![image](https://github.com/guansss/pixi-live2d-display/assets/46285865/fe6f5212-f367-43b1-bc98-d26e798377a5)

Seems to work for me. Could be a cache problem, maybe try deleting your `node_modules`, `yarn.lock` or something.
