### ISSUE TITLE
关于项目完全离线本地化

### ISSUE THREAD

**Issue by bingoyesbingoyes** [guansss/pixi-live2d-display#116]
<script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/dylanNew/live2d/webgl/Live2D/lib/live2d.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pixi.js@6.5.2/dist/browser/pixi.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pixi-live2d-display/dist/index.min.js"></script>
请问，这几个cdn如何实现本地化静态调用呢
我尝试直接将对应网页内容复制下来保存到本地js，但引用过程中还是提示了有其他缺少项

**Comment by guansss** [comment]
请提供错误信息和最小复现
