### ISSUE TITLE
如何在框架内修改模型参数

### ISSUE THREAD

**Issue by Longtianmu** [guansss/pixi-live2d-display#119]
如题，请问框架是否有提供相关能力的计划？
现阶段有其他实现么？
谢谢

**Comment by Longtianmu** [comment]
具体而言，问题已经解决，是修改模型的Parameters如ParameterEyeBallX等。
在得到InternalModel后，强制断言转换为Cubsim4Model等即可。
但是这样强制转换好像不太优雅，请问有其他方法或有相关计划么？

**Comment by guansss** [comment]
可以用 `model instanceof Cubism4InternalModel`

**Comment by guansss** [comment]
一般是不会加的，因为不同版本模型的 API 差异很大，无法顾及到全部

不过 set param 这种比较常用的以后可能会加一下
