### ISSUE TITLE
如何正常的切换一个模型的纹理(Texture)

### ISSUE THREAD

**Issue by loclink** [guansss/pixi-live2d-display#132]
![image](https://github.com/guansss/pixi-live2d-display/assets/106688231/432ef0d6-ea9c-4de0-b7eb-289a92326cf9)

我使用此方式切换Texture时, 某些模型展示正常,而某些模型出现了无法预料的结果

![61](https://github.com/guansss/pixi-live2d-display/assets/106688231/77dc8bc3-5917-4b53-929f-ab4436413375)

![image](https://github.com/guansss/pixi-live2d-display/assets/106688231/c6bd5749-5c9f-4a4d-a4a4-edf55198e456)

**Comment by loclink** [comment]
望回复, 不太清楚是我使用方式有问题还是模型本身存在问题

**Comment by guansss** [comment]
请提供最小复现

**Comment by loclink** [comment]
感谢答复
这个model.ts包含了所有模型的setting操作
https://github.com/oh-my-live2d/oh-my-live2d/blob/master/packages/oh-my-live2d/src/modules/model.ts#L72

这里包含实例化操作之后的调用
https://github.com/oh-my-live2d/oh-my-live2d/blob/master/packages/oh-my-live2d/src/modules/index.ts#L151
- 正常的模型:
https://model.oml2d.com/pio/model.json

- 异常的模型:
https://cdn.jsdelivr.net/gh/guansss/pixi-live2d-display/test/assets/shizuku/shizuku.model.json

这是一个完整的项目, 不确定您是否可以根据这些判断出问题, 看您还需要哪些信息,我这边随时可以提供

**Comment by guansss** [comment]
感谢你的理解，但这个并不是最小复现，关于如何创建最小复现，请查看[这篇文章](https://izhangzhihao.github.io/2021/06/06/%E8%A7%A3%E5%86%B3-Bug-%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF/)或者[这篇文章](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by loclink** [comment]
<https://codepen.io/loclink/pen/zYXGYjo>

了解, 我这里准备了一个demo, 当点击切换按钮时这个问题将被复线, 同时表现正常的模型包含在注释中

**Comment by loclink** [comment]
抱歉, 才发现大部分的模型的纹理必须是按顺序重叠展示的, 而有些模型的每个纹理都是完整的, 这是一个理解上的错误, 这个issue到这就关闭了, 感谢您的答复

**Comment by He-Chao** [comment]
> 抱歉, 才发现大部分的模型的纹理必须是按顺序重叠展示的, 而有些模型的每个纹理都是完整的, 这是一个理解上的错误, 这个issue到这就关闭了, 感谢您的答复

你好，我在切换纹理时也遇到这个问题，当前模型是有两个纹理图堆叠的（texture_00.png,texture_01.png），现在要切换（texture_00.png,texture_01.png）到（texture_02.png,texture_03.png），请教一下你是如何实现的呢？我尝试用[texture_00.png,texture_01.png],[texture_02.png,texture_03.png]会黑屏
