### ISSUE TITLE
使用移动端edge等浏览器无法正常显示模型

### ISSUE THREAD

**Issue by jacksen168sub** [guansss/pixi-live2d-display#134]
![QQ截图20240303164002](https://github.com/guansss/pixi-live2d-display/assets/157391308/f76584a9-37fd-4312-a0bf-1b28a6b708a2)
电脑端显示正常
![QQ截图20240303164358](https://github.com/guansss/pixi-live2d-display/assets/157391308/639300bf-239b-45ec-ac81-94a28f00b73c)
环境打包：
[test.zip](https://github.com/guansss/pixi-live2d-display/files/14472246/test.zip)

**Comment by guansss** [comment]
应该是因为纹理尺寸太大了，我把 texture_00.png 缩小一半之后就可以显示了

我的手机浏览器上 `gl.MAX_TEXTURE_SIZE` 测出来最大尺寸是 4096，而 texture_00.png 的大小是 8192x4096，所以缩小一半到 4096x 2048 才符合要求

以后我会考虑加入一些自动缩放纹理的功能，这样就不用手动处理了

**Comment by jacksen168sub** [comment]
> 应该是因为纹理尺寸太大了，我把 texture_00.png 缩小一半之后就可以显示了
> 
> 我的手机浏览器上 `gl.MAX_TEXTURE_SIZE` 测出来最大尺寸是 4096，而 texture_00.png 的大小是 8192x4096，所以缩小一半到 4096x 2048 才符合要求
> 
> 以后我会考虑加入一些自动缩放纹理的功能，这样就不用手动处理了

祝你的项目v0.5.0正式版早日孵化吧😉

**Comment by HHaidai** [comment]
我也遇到了这个问题，请问是怎么手动缩小纹理尺寸的？

**Comment by Yorenzz** [comment]
> 我也遇到了这个问题，请问是怎么手动缩小纹理尺寸的？

压缩图片像素
