### ISSUE TITLE
Do I need a license for Cubism SDK?

### ISSUE THREAD

**Issue by mrskiro** [guansss/pixi-live2d-display#138]
Thanks for the great library.

I would like to make commercial use of a product implementing this library.

In that case, I assume this library uses Cubism Core, do I need to obtain a license for this?

https://www.live2d.com/sdk/license/

**Comment by guansss** [comment]
Yes, you need to obtain the license to use the Cubism Core, I don't know how though.

**Comment by mrskiro** [comment]
Okay, thanks!
