### ISSUE TITLE
Something happened on Test

### ISSUE THREAD

**Issue by RaSan147** [guansss/pixi-live2d-display#141]
The dl link for test is not working

Kindly check this
https://github.com/RaSan147/pixi-live2d-display/actions/runs/8630374063/job/23656499749#step:9:30

**Comment by guansss** [comment]
Google recently changed the Chrome driver's download URL, to fix it you need to upgrade some dependencies like in this commit: https://github.com/guansss/pixi-live2d-display/pull/122/commits/6f3cd68a5e8354f259e0eb8ba98de540bd0b017c

**Comment by RaSan147** [comment]
Thanks, will test and close issue asap
