### ISSUE TITLE
vue2 集成 pixi-live2d-display 模型未成功加载

### ISSUE THREAD

**Issue by lakako** [guansss/pixi-live2d-display#142]
代码地址：https://github.com/lakako/live2ddebug

启动后无法正常显示人物，且没有报错

将`import * as PIXI from 'pixi.js'` 删除，并将

```
  <script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/dylanNew/live2d/webgl/Live2D/lib/live2d.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/pixi.js@6.5.2/dist/browser/pixi.min.js"></script>
```
添加到index.html的body中，可以正常展示模型，但是在执行动作的时候有概率出现 #109 中提到的问题

想问问是是不是我哪儿配错了？

**Comment by guansss** [comment]
你项目里的 pixi.js 并没有正常加载，实际上不仅模型，其他物体也无法显示

我调试了一下，感觉依赖文件被加载得很混乱，估计是 Vue CLI 的版本太旧了

你可以试着升级一下 Vue CLI 和其他配套的依赖，至少先把 pixi.js 正常运行起来

**Comment by lakako** [comment]
时候vue-cli重新创建项目后，问题解决

谢谢
