### ISSUE TITLE
移动端模型比较模糊

### ISSUE THREAD

**Issue by HHaidai** [guansss/pixi-live2d-display#146]
<img width="425" alt="企业微信截图_17140284496385" src="https://github.com/guansss/pixi-live2d-display/assets/115163343/72836749-7506-4125-a5eb-5f64963c2743">
左边是使用该库生成的模型，右边是live2d web sdk生成的模型，相比之下左边模糊了许多，我个人推测是纹理渲染导致的问题，期待作者进行修复

**Comment by Mios-dream** [comment]
渲染出来模型比较糊是因为PIXI的默认渲染器的分辨率的问题,使用resolution参数，并设置为更高值(默认为1)即可解决。
```
    this.app = new PIXI.Application({
      view: this.canvasElement,
      resizeTo: this.canvasElement,
      backgroundAlpha: 0,
      autoStart: true,
      // 允许保存画布,便于获取画布数据
      preserveDrawingBuffer: true,
      resolution: 2,
    })
```
添加之前
<img width="442" height="430" alt="Image" src="https://github.com/user-attachments/assets/6713706e-e676-4b9e-9b98-2ee63cb16da0" />
修改之后
<img width="427" height="439" alt="Image" src="https://github.com/user-attachments/assets/5920a6cb-cea7-44c2-9851-db1c649c9c4a" />
