### ISSUE TITLE
口型同步能力能否优化？

### ISSUE THREAD

**Issue by liyao1520** [guansss/pixi-live2d-display#150]
[live2d官网](https://www.live2d.com/zh-CHS/learn/sample/)模型的演示视频嘴型是可以比较灵活展示的，口型和声音看起来也比较自然.
[演示视频](https://www.bilibili.com/video/BV1B8411v7bi/?spm_id_from=888.80997.embed_other.whitelist&t=8.156311&bvid=BV1B8411v7bi&vd_source=45832582e343ad0c97fd2d4f2b4f158c)
这个示例模型，不仅可以通过音频信息可以来设置嘴巴开合程度，还可以通过设置`ParamA`、'ParamE'、'ParamI'、'ParamO'、'ParamU'，来设置元音口型

```js
 model.internalModel.coreModel.setParameterValueById('ParamMouthOpenY', mouthY)
 model.internalModel.coreModel.setParameterValueById('ParamA', 0.3)
```
我感觉有更好的方法实现口型同步，能否根据音频让模型设置对应口型？

还有阿里云的TTS可输出每个汉字/英文单词在音频中的时间位置，如何模型播放音频，能否根据拼音信息设置对应口型？

求大佬们指教！🙏

**Comment by cacard** [comment]
官方提供的口型驱动是基于5中英语长元音（AEIOU）的，中文支持的不好；要想进一步做好，需要支持中文多种发音（貌似有几十个）的驱动解决方案。
