### ISSUE TITLE
Failed to load motion: TypeError: Cannot set property 'time' of undefined

### ISSUE THREAD

**Issue by KAIYOHUGO** [guansss/pixi-live2d-display#16]
## warning
```js
index.min.js:formatted:142 [MotionManager(jianye_2)] Failed to load motion: motions/idle.motion3.json
 TypeError: Cannot set property 'time' of undefined
    at q.parse (index.min.js:formatted:3383)
    at Function.create (index.min.js:formatted:3203)
    at $.createMotion (index.min.js:formatted:3474)
    at index.min.js:formatted:584
```

and I  try Live2D Viewer Online (WIP),and it's  work!

# 🤔 

i don't  know how to fix that ,I am not good at ts,so pls help 👏🏼

**Comment by guansss** [comment]
Hi. This is a known bug of the official framework and has been fixed, the fix will be released soon. The reason that it works in Live2D Viewer Online is just that I've made a quick fix in that project.

**Comment by KAIYOHUGO** [comment]
thank u very much!
