### ISSUE TITLE
File upload error TypeError

### ISSUE THREAD

**Issue by yeemachine** [guansss/pixi-live2d-display#17]
I've been using both beta.1 and beta.2 version atm and it seems you've removed support for DataUrls for uploading models? 
```
File upload error TypeError: The `url` property must be specified in settings JSON
```
I was getting the browser crashing error when upload a mix of Cubism 2.0 and Cubism 4.0 models until I updated to the beta.2. But now, when uploading an object into `Live2DModel.from()` with dataurls instead of file paths, the plugin no longer accepts them. Is there a workaround for this?

**Comment by guansss** [comment]
Yes, previously the `url` will default to an empty string if it's not defined in the JSON, until I realized that not setting a URL for the JSON would typically result in errors, even if it gets a default value.

You can still workaround it by assigning an empty string when you've taken good care of all the URLs in the JSON.

```
json.url = '';

Live2DModel.from(json);
```

**Comment by yeemachine** [comment]
Thank for the quick response. That seems to do the trick!
