### ISSUE TITLE
Weird interval between every idle motion play.

### ISSUE THREAD

**Issue by dannylin0711** [guansss/pixi-live2d-display#21]
Already set the motionFadingDuration and idleMotionFadingDuration to 0, but it doesn't work like the idle motion interval in Cubism Viewer, which is continuous and would not stop the previous idle animation before the next idle animation play.

**Comment by guansss** [comment]
I don't get it, that sounds like it's working as expected, since setting the fading duration to 0 means there will be an instant transition between two motions.

**Comment by dannylin0711** [comment]
The idle animations should not have any transition between it, I think. It should loop smoothly, instead of looping with transition between every individual animation.

**Comment by guansss** [comment]
I'm still not clear, hmm, isn't "smoothly" equivalent to "with transition"? Or perhaps, did you mean to let the model loop a single idle motion instead of looping between multiple idle motions?

**Comment by dannylin0711** [comment]
Ummm, yeah that's probably what I mean, there is a weird interval the model just stop animating when transition between the idle motion(one idle animation only)

**Comment by dannylin0711** [comment]
[Example](https://cdn.discordapp.com/attachments/665275245841743905/816644289182040064/ezgif.com-gif-maker.gif)

**Comment by dannylin0711** [comment]
[Example of looping single idle motion without interval using offical cubism viewer](https://im4.ezgif.com/tmp/ezgif-4-7e5fd8d2525b.gif)

**Comment by guansss** [comment]
OK I get it, this is a problem indeed, I'll investigate it.

**Comment by guansss** [comment]
Well, I realized setting the duration to 0 can actually fix this problem. The reason it doesn't work in your case is probably because the durations are overwritten by the ones that the idle motion defines. You can check if the idle motion in your model's settings file looks like this:

```json
{"file": "abc.mtn", "fade_in": 2000, "fade_out": 2000}
```

If so, removing the `fade_in` and `fade_out` should fix it.

And if it's a model of Cubism 3 or 4, the keys will instead be `FadeInTime` and `FadeOutTime`.

**Comment by dannylin0711** [comment]
Ok, I will look into that,thanks!

**Comment by dannylin0711** [comment]
<img width="291" alt="截圖 2021-03-05 上午8 28 16" src="https://user-images.githubusercontent.com/43667063/110049413-bfb2ed80-7d8c-11eb-915d-6dba30b9832c.png">
OK, so I open up the motion.json, and the FadeInTime and FadeOutTime are both 0.0.

**Comment by guansss** [comment]
You need to check the model.json as well, because the durations will only be read from the model.json, and those in motion.json will be ignored. This is basically another bug that I'll fix later.

**Comment by dannylin0711** [comment]
I didn't see that two parameters in my model.json , hmmm.

**Comment by guansss** [comment]
That's strange, I've tested various models and they all behaved well.

Could you share the model you used so I can test with it? If it's a proprietary model, you can replace the textures with solid black images before sharing, in order to prevent any potential abuse.

**Comment by dannylin0711** [comment]
[left_sen.zip](https://github.com/guansss/pixi-live2d-display/files/6095155/left_sen.zip)
I've also test the models with the viewer in the readme.md, the problem stills happen.

**Comment by guansss** [comment]
Thanks.

During the test, I can still see that it makes difference when setting 0 durations, as the picture below, the left model gets 0 durations applied and the right model remains default.

![Honeycam 2021-03-06 22-24-23](https://user-images.githubusercontent.com/46285865/110210116-2fc78d80-7ecb-11eb-96f6-85a590e8c783.gif)

Here's how the config should be set up, did you do it like this?

```js
import { config } from 'pixi-live2d-display';

config.idleMotionFadingDuration = 0;
```

**Comment by dannylin0711** [comment]
Yes, that's what I did. 
This set of models' motion changes expression(not using the expressions in Live2D), so some models would stop at the end of the motion and give a weird face in the time between the motions.

**Comment by dannylin0711** [comment]
I'm not sure not this is the correct usgae
`const live2d = PIXI.live2d;`
and use it as 
`live2d.config.motionFadingDuration = 0;
 live2d.config.idleMotionFadingDuration = 0;
 live2d.config.expressionFadingDuration = 0;`
 I did not use nodeJS.

**Comment by dannylin0711** [comment]
https://github.com/dannylin0711/SDVX-Wallpaper
This is the project, the code is open to public, but not the model.

**Comment by dannylin0711** [comment]
Okay so I actually made some idiot error
I initialize the model before I change the config
BEFORE
```js
let modelData = await live2d.Live2DModel.from(jsonPath, { idleMotionGroup: 'Idle', motionPreload: "ALL" });
...
live2d.config.motionFadingDuration = 0;
live2d.config.idleMotionFadingDuration = 0;
live2d.config.expressionFadingDuration = 0;
```
AFTER
```js
live2d.config.motionFadingDuration = 0;
live2d.config.idleMotionFadingDuration = 0;
live2d.config.expressionFadingDuration = 0;
...
let modelData = await live2d.Live2DModel.from(jsonPath, { idleMotionGroup: 'Idle', motionPreload: "ALL" });
```
I firstly thought that model have the duration time set already, so I should edit the time after I initialize the model, however I just fiqure out while I was taking a shower that the config show be changed before I initialize the model if the model didn't specify a fadein/out value.

**Comment by dannylin0711** [comment]
Hope that the fade in/out timing would implement in the future, good work and thanks for helping

**Comment by guansss** [comment]
Even I didn't think of this possibility, it's good to see it works.

**Comment by dannylin0711** [comment]
Sorry, I would like to ask if there's a way to custom the auto focus function(e.g. disable the auto focus, and add my own event listener) on cursor?

**Comment by guansss** [comment]
Sure, you can disable the `autoInteract` option like [this](https://github.com/guansss/pixi-live2d-display/wiki/Complete-Guide#manually-1)

**Comment by dannylin0711** [comment]
Thanks!
