### ISSUE TITLE
Animate eyes blinking and mouth opening in cubism v4?

### ISSUE THREAD

**Issue by thisismygatekeeper** [guansss/pixi-live2d-display#40]
I was following https://github.com/guansss/pixi-live2d-display/issues/4 and got cubism v2 to work properly. However, 
```
model.internal.eyeBlink.setEyeParams(eyeValue)
```
and 
```
model.internalModel.coreModel.setParamFloat('PARAM_MOUTH_OPEN_Y', mouthSize);
```
didn't work - `setEyeParams` isn't available in `eyeBlink` and `setParamFloat` doesn't seem to be available in `coreModel`. Could you kindly suggest some way out? Thank you!

**Comment by thisismygatekeeper** [comment]
ok found the corresponding functions in v4.

**Comment by Panzer-Jack** [comment]
I also have this problem. How did you receive it ?
