### ISSUE TITLE
PIXI.graphics disappears with the use of some Live2D models

### ISSUE THREAD

**Issue by yeemachine** [guansss/pixi-live2d-display#5]
I've been starting to build out more features with pixi-live2D-display, though I'm finding some weird bugs when using PIXI.graphics. It appears that some models, like the one you've provided [Shizuku] is overwriting the render of PIXI.graphics. If I switch it to some other models I have in the linked [Pen](https://codepen.io/yeemachine/pen/JjXvbdO), graphics render normally. Could this be a conflict with the expression or motion managers?

**Comment by guansss** [comment]
Fixed, thanks for reporting!
