### ISSUE TITLE
Any plans to support Pixi.js 6+ or Cubism 4.2?

### ISSUE THREAD

**Issue by yeemachine** [guansss/pixi-live2d-display#52]
Just curious if there were any plans to support the latest version of PixiJS or the newly released spec for Live2D.

**Comment by guansss** [comment]
Yes, I had the plan, but have been lacking the motivation to give it priority. I'm the one who's just too lazy to take the step until someone pushes me a bit. 😑 Now I'll see if I have the time and start to work on it.

**Comment by yeemachine** [comment]
Haha that makes sense. For what it's worth, I've been pointing to your repo as the best Live2D web renderer web. I imagine there will be even more vtuber webapps that want to use it in the future.

I've been wanting to use some cool prebuilt effects like https://github.com/pixijs/pixi-lights in my apps, but that is only compatible with pixi 6+. Thanks again for the library!

**Comment by guansss** [comment]
Hopefully! Thanks for the promotion, I'll try to make the project live up to this honor! 😉
