### ISSUE TITLE
关于HitAreaFrames

### ISSUE THREAD

**Issue by eipip1e0** [guansss/pixi-live2d-display#54]
大佬您好，
您在[Interaction demo](https://codepen.io/guansss/pen/KKgXBOP/left?editors=0010)中使用了HitAreaFrames。
然而我通过npm安装，却找不到HitAreaFrames如何导入？请问我应该怎么做？

**Comment by guansss** [comment]
你好，该文件在 node 环境中需要直接使用源码，并且需要 TypeScript 环境，具体请查看 [文档](https://guansss.github.io/pixi-live2d-display/additional/#hitareaframes)

**Comment by eipip1e0** [comment]
知道了，谢谢您
