### ISSUE TITLE
 Help me plz

### ISSUE THREAD

**Issue by IntroEvEivie** [guansss/pixi-live2d-display#55]
A bit of a stupid question. I need to pass the URL value from the button to the asynchronous main function to display this model. How to replace models in view mode?

**Comment by guansss** [comment]
Just add a parameter to the main function.

```js
async function main (url) {
    const model = await Live2DModel.from(url);

    // ...
}

main("model.json");
```

**Comment by IntroEvEivie** [comment]
> Just add a parameter to the main function.
> 
> ```js
> async function main (url) {
>     const model = await Live2DModel.from(url);
> 
>     // ...
> }
> 
> main("model.json");
> ```

Thx. Give me your discord if possible

**Comment by guansss** [comment]
Nope, I don't have a discord.
