### ISSUE TITLE
关于hitArea与motion的绑定问题

### ISSUE THREAD

**Issue by eipip1e0** [guansss/pixi-live2d-display#56]
对于`Live2DViewerEX`这款软件，它能够通过读取配置文件`*.motion3.json`中的`HitAreas`，实现`hitArea`与`motion`的绑定，也能设定与`hitArea`绑定的`motion`优先级，以解决hitArea的重叠问题。
例如：
```json
{
...
"HitAreas": [
    {
      "Name": "TouchHead",
      "Id": "TouchHead",
      "Order": 1,
      "Motion": "TapTouchHead"
    },
    {
      "Name": "TouchBody",
      "Id": "TouchBody",
      "Order": 1,
      "Motion": "TapTouchBody"
    },
    {
      "Name": "TouchSpecial",
      "Id": "TouchSpecial",
      "Order": 2,
      "Motion": "TapTouchSpecial"
    },
    {
      "Name": "shu",
      "Id": "shu",
      "Motion": "Tapshu"
    },
    {
      "Name": "paozuo",
      "Id": "paozuo",
      "Order": 1,
      "Motion": "Settings"
    }
...
}
```
其中`Order`给定了动作的优先级；`Motion`绑定了名为`Name`的hitArea。

然而，翻阅您的文档后，我并未在您的项目中找到类似的接口。在您给的范例中，也是在检测到指定`hitArea`之后，再指定需要执行的动作，这样是否有点太麻烦了？
不知是否是我看漏了？不知您能否加入与Live2DViewerEx类似的功能？

看了以下您的源码，然而我不熟悉前端。是否可以在以下模块中添加中添加order和motion字段，以实现相应功能？
`InternalModel.ts`
`Cubism2InternalModel.ts`
`Cubism4InternalModel.ts`
`Cubism2Spec.d.ts`
`CubismSpec.d.ts`
....

**Comment by guansss** [comment]
这个是 Live2DViewerEX 的应用特定功能，并非 Live2D 本身的功能，也就是说为该应用定制的 model.json 只能在该应用里正常使用

而本项目不是应用，是一个通用的开发库，所以不会加入此类非常客制化的功能

**Comment by eipip1e0** [comment]
了解啦，谢谢回复！:blush:
