### ISSUE TITLE
模型部件透明度显示异常

### ISSUE THREAD

**Issue by eipip1e0** [guansss/pixi-live2d-display#57]
很抱歉又来打扰您了。
# 问题描述
- 问题模型：
-- [Ava](https://github.com/eipip1e0/BlogCDN/tree/master/Blog/live2d/Cubsim4/Ava)
-- [Ava.model3.json的CDN](https://cdn.jsdelivr.net/gh/eipip1e0/BlogCDN@v0.1.3/Blog/live2d/Cubsim4/Ava/Ava.model3.json)
- 模型`部件`的透明状态不能正常显示，所有`部件`均以非透明状态显示出来。
- 正常状态：
![image](https://user-images.githubusercontent.com/31157354/167616739-0367d1a7-7225-4d04-b309-e9f745325a6f.png)
- 实际状态：
![image](https://user-images.githubusercontent.com/31157354/167617981-4e8d2cfd-4e2f-43c7-b092-1bb9b3c2e214.png)
# 该模型的测试环境
|测试环境|测试结果|
|-|-|
|自行打包的您的项目|不正常|
|[Cubism SDK for Web](https://www.live2d.com/download/cubism-sdk/download-web/)|不正常|
|[Cubism SDK for Unity](https://www.live2d.com/download/cubism-sdk/download-unity/)|不正常（貌似不能测试motion）|
|[Live2D Viewer Online](https://guansss.github.io/live2d-viewer-web/)|不正常|
|Live2DViewerEX中，motion的混合模式（BlendMode）= 叠加|不正常|
|Live2DViewerEX中，motion的混合模式（BlendMode）= 覆盖|正常|

# 尝试
阅读官方源码，然而水平有限没找到是哪里的问题。
可能相关的字段：
- `CubismBlendMode` 
- `setParameterValueByIndex` 
- `CubismMotionCurveTarget_PartOpacity` 

# 原因猜测：
- motion3.json中`"Target": "PartOpacity"`的`Curves`未能正常加载
# 希望
如果可以的话，能让该模型正常显示

**Comment by guansss** [comment]
可否提供一下模型的压缩包，我这边难以通过CDN下载模型

**Comment by eipip1e0** [comment]
> 可否提供一下模型的压缩包，我这边难以通过CDN下载模型

努力了两天，就在刚刚，我找到并修复了这个bug，已经提交pr了。不过没经过大量测试，不知会不会对其他地方产生影响
[CubismWebFramework](https://github.com/guansss/CubismWebFramework)

**Comment by eipip1e0** [comment]
问题模型：

[Ava.zip](https://github.com/guansss/pixi-live2d-display/files/8675482/Ava.zip)
