### ISSUE TITLE
Model animating tongue out action?

### ISSUE THREAD

**Issue by thisismygatekeeper** [guansss/pixi-live2d-display#58]
Is it possible to use `coreModel.setParameterValueById` to control the tongue out motion?

**Comment by eipip1e0** [comment]
> Is it possible to use `coreModel.setParameterValueById` to control the tongue out motion?

how about changing the `*.motion.json` file to perform your specific motion ？

**Comment by guansss** [comment]
Yes it's possible, are you experiencing any problem using this?

**Comment by thisismygatekeeper** [comment]
Hmm I couldn't find the right `id` for the tongue out parameter https://docs.live2d.com/cubism-editor-manual/standard-parametor-list/?locale=en_us. Would you mind sharing how you control it? Thanks!

**Comment by guansss** [comment]
You need a model that actually provides some kind of parameter for the tongue. The standard parameters are just a recommendation, not a requirement to the models.
