### ISSUE TITLE
示例cdn地址均无法访问

### ISSUE THREAD

**Issue by z821922141** [guansss/pixi-live2d-display#63]

**Comment by guansss** [comment]
我这边访问正常，如果无法访问那九成九是墙的问题

**Comment by z821922141** [comment]
> 我这边访问正常，如果无法访问那九成九是墙的问题

https://cdn.jsdelivr.net/npm/pixi-live2d-display/dist/index.min.js  我可以在其他哪个没墙影响的地方拿到这个文件呢

**Comment by guansss** [comment]
jsdelivr 应该是有国内节点的，也许是暂时抽风了，可以试一下换成 unpkg 或者 cdnjs

**Comment by z821922141** [comment]
> jsdelivr 应该是有国内节点的，也许是暂时抽风了，可以试一下换成 unpkg 或者 cdnjs

好像都不行

**Comment by guansss** [comment]
不至于吧，这几个就是最大的 cdn 服务商了，如果都连不上那你大部分网站都打不开了

**Comment by z821922141** [comment]
> 不至于吧，这几个就是最大的 cdn 服务商了，如果都连不上那你大部分网站都打不开了

从反馈这个的时候到现在我都访问不了

**Comment by guansss** [comment]
那就不清楚了，请自行解决网络问题
