### ISSUE TITLE
能否隐藏或者显示模型的某一个部分？

### ISSUE THREAD

**Issue by SyraTi** [guansss/pixi-live2d-display#64]
## 问题表现
我的模型目前似乎所有的手部都会展示。官方的WebSDK也是如此。

![Q~4X_D}}S24Z~V 7ZOG~8YL](https://user-images.githubusercontent.com/20638533/173481253-5b480835-919c-4142-b4a2-922b31bcb411.png)

## 说明

我尝试了 https://github.com/DenchiSoft/CubismViewerGems 这个unity项目，发现似乎可以调整部件的透明度来隐藏不需要的手部。
![image](https://user-images.githubusercontent.com/20638533/173481756-4efa7409-fa2d-47dc-982a-f8414cd6543e.png)

请问本项目可以实现吗？ 附上我使用的模型 ↓
[object_live2d_002_101.asset.zip](https://github.com/guansss/pixi-live2d-display/files/8895858/object_live2d_002_101.asset.zip)

**Comment by guansss** [comment]
隐藏部位一般是通过加载 pose 来实现的，另外也可以通过代码来实现，看你的例子应该是 Cubism 4，对应的函数是 `model.internalModel.coreModel.setPartOpacityById(partId, opacity)`

**Comment by SyraTi** [comment]
> 隐藏部位一般是通过加载 pose 来实现的，另外也可以通过代码来实现，看你的例子应该是 Cubism 4，对应的函数是 `model.internalModel.coreModel.setPartOpacityById(partId, opacity)`

感谢，通过代码确实能够隐藏了，但是我看到一些motions3.json的Curves字段中也包含了PartOpacity类似的内容，是否motion中定义了PartOpacity，但是没有识别呢？
```json5
// 文件路径 /motions/LIVE2D_002_101_20.motion3.json 302:18
[{
      "Target": "PartOpacity",
      "Id": "PartRightHand07",
      "Segments": [
        0,
        0,
        0,
        0.02,
        0
      ]
    },
    {
      "Target": "PartOpacity",
      "Id": "PartRightHand06",
      "Segments": [
        0,
        0,
        0,
        0.02,
        0
      ]
    },
    {
      "Target": "PartOpacity",
      "Id": "PartRightHand05",
      "Segments": [
        0,
        1,
        0,
        0.02,
        1
      ]
    }
]
```
我不知道您说的pose是否和motion3.json有关？
抱歉虽然我觉得这个应该是Live2D sdk的内容，但是我没有太多l2d的基础，希望能得到帮助解决一下 感谢

**Comment by SyraTi** [comment]
看起来是submodule没有更新导致的， 更新了submodule，提交了pr #65

**Comment by guansss** [comment]
> 看起来是submodule没有更新导致的， 更新了submodule，提交了pr #65

确实没有更新，因为我在等这个 pr 得到解决：https://github.com/Live2D/CubismWebFramework/pull/11

之前我也觉得这是个 bug，于是接受了 submodule 那边的 pr，但 live2d 的官方认为不是 bug（虽然我不太认同官方的解释），所以取决于最终的处理结果，那个 pr 有可能需要回退，和官方行为保持一致

**Comment by SyraTi** [comment]
> > 看起来是submodule没有更新导致的， 更新了submodule，提交了pr #65
> 
> 确实没有更新，因为我在等这个 pr 得到解决：[Live2D/CubismWebFramework#11](https://github.com/Live2D/CubismWebFramework/pull/11)
> 
> 之前我也觉得这是个 bug，于是接受了 submodule 那边的 pr，但 live2d 的官方认为不是 bug（虽然我不太认同官方的解释），所以取决于最终的处理结果，那个 pr 有可能需要回退，和官方行为保持一致

好的了解了 看了官方的文档 给模型添加Pose解决了  感谢你的解答！

**Comment by SyraTi** [comment]
这个Issue和关联的PR我就一起关闭了

**Comment by eipip1e0** [comment]
> > 看起来是submodule没有更新导致的， 更新了submodule，提交了pr #65
> 
> 确实没有更新，因为我在等这个 pr 得到解决：[Live2D/CubismWebFramework#11](https://github.com/Live2D/CubismWebFramework/pull/11)
> 
> 之前我也觉得这是个 bug，于是接受了 submodule 那边的 pr，但 live2d 的官方认为不是 bug（虽然我不太认同官方的解释），所以取决于最终的处理结果，那个 pr 有可能需要回退，和官方行为保持一致

在别的分支找到了和我一样的修改🤦‍♂️，还是2020年。[[Fix] Part Opacity Motion](https://github.com/DreDiki/CubismWebFramework/commit/e013170a71be436c27b6768b0c184a57ee63c776)
官方的解释我也不太认同，只能认为是一种规范吧，但是这种规范对于某些缺少pose文件的模型是一种麻烦。😣

**Comment by guansss** [comment]
@TillMac pose 是根据 model3.json 的定义来加载的，如果里面有定义，在 `Live2DModel.from()` 的时候就会自动加载

**Comment by TillMac** [comment]
原来是我理解错误，谢谢你快速回复我！
