### ISSUE TITLE
Expression表现似乎和官方不一致

### ISSUE THREAD

**Issue by SyraTi** [guansss/pixi-live2d-display#67]
## 问题表现
同一份expression文件，Cubism Viewer中显示正常（右），使用本仓库展示时瞳孔缩放出现问题（左）
![image](https://user-images.githubusercontent.com/20638533/175477649-da12671d-456f-4725-b363-95c3ab6c813e.png)

## 复现代码
```javascript
model.expression('F06')
```

## 问题模型
[object_live2d_002_101.asset.zip](https://github.com/guansss/pixi-live2d-display/files/8973776/object_live2d_002_101.asset.zip)
## 问题Expression
/expressions/LIVE2D_002_101_06.exp3.json

**Comment by guansss** [comment]
感谢反馈，已修复问题

**Comment by SyraTi** [comment]
> 感谢反馈，已修复问题

这个修改是在dev分支上  请问大概什么时候会进正式版本发布到npm呢

**Comment by guansss** [comment]
新版本升级了不少依赖，需要多检查一下兼容性，如果顺利的话预计这周末或者下周发布
