### ISSUE TITLE
Adjust physics strength?

### ISSUE THREAD

**Issue by thisismygatekeeper** [guansss/pixi-live2d-display#68]
Is there a parameter I can use to tune up / down the physics strength? Vtube studio has a physics slider and it can make the character movement smooth like silk. Can we do something similar here too? Thanks!
<img width="555" alt="Screen Shot 2022-06-27 at 3 18 48 PM" src="https://user-images.githubusercontent.com/96497730/176045203-f6e1f614-5440-41bc-8f70-545378669afe.png">

**Comment by guansss** [comment]
I don't know what it looks like, and it seems to be out of scope of this plugin. You can check the source code ([cubism2](https://github.com/guansss/pixi-live2d-display/blob/master/src/cubism2/Live2DPhysics.ts), [cubism 4](https://github.com/guansss/CubismWebFramework/tree/aba961a83b8d43dd047f1420fddbb4b5f7860505/src/physics)) and see if there are parameters that can be adjusted.
