### ISSUE TITLE
如何在call model.motion的时候保留现有的expression

### ISSUE THREAD

**Issue by randysu** [guansss/pixi-live2d-display#69]
大佬您好，我在live2d viewer当中play motion时会保留现有的表情（expression），但是本库在唤起model.motion的时候会把表情覆盖为默认然后再播放 motion

**Comment by guansss** [comment]
目前可以通过覆盖 `MotionState#shouldOverrideExpression` 并始终返回 false 来实现，下个版本我会加一个选项来控制该行为

**Comment by randysu** [comment]
谢谢大佬，我试试自己改Typescript build 一下

**Comment by guansss** [comment]
0.4.0-beta.2 已默认禁用该行为，如有需要可通过 `config.preserveExpressionOnMotion = false` 来重新开启
