### ISSUE TITLE
import問題

### ISSUE THREAD

**Issue by Cpk0521** [guansss/pixi-live2d-display#76]
package.json
![pack](https://user-images.githubusercontent.com/10280294/189513733-2a47f3b1-d3d7-4e9f-960d-3888e21476af.png)

問題
![unknown](https://user-images.githubusercontent.com/10280294/189513740-91cfd9a3-79a2-41e6-a2c7-7cd0876296d8.png)

根據document的做法

```
// if only Cubism 4
import { Live2DModel } from 'pixi-live2d-display/cubism4';
```
卻無法import模組

**Comment by guansss** [comment]
TS 对这种 import 方式的支持还不是很好，可以把 tsconfig 里的 moduleResolution 设为 `nodenext`，然后重启一下 TS 服务或者直接重启 vscode

```json
{
  "compilerOptions": {
    "moduleResolution": "nodenext"
  }
}
```

**Comment by Cpk0521** [comment]
好的 我稍後會嘗試
