### ISSUE TITLE
如何加载live2d_3的动画motions？

### ISSUE THREAD

**Issue by tomiaa12** [guansss/pixi-live2d-display#83]
![image](https://user-images.githubusercontent.com/34568691/201623628-5d942bb1-be8e-48fb-a49f-91178877345d.png)

**Comment by tomiaa12** [comment]
![image](https://user-images.githubusercontent.com/34568691/201636130-e8b04366-366a-4a22-87f2-579bdccf4f06.png)
temp2就是model，但是我motion调用并没有触发动画

**Comment by tomiaa12** [comment]
解决了，还是通过model.motion()触发，得看json文件的motions的分组名称

**Comment by XXig** [comment]
> 解决了，还是通过model.motion()触发，得看json文件的motions的分组名称

请教一下，这个是哪里看的呢？
