### ISSUE TITLE
关于 ❶待机动画不能正常循环  & ➋控制器Controllers的API

### ISSUE THREAD

**Issue by Fpppps** [guansss/pixi-live2d-display#84]
首先，非常感谢作者提供的Live2D插件，极大的方便了Live2D模型的应用；
其次，个人在应用的过程出现了未能解决的问题，希望能得到大家的回复；
最后，也是希望这款插件越来越完善，被更大范围的应用起来。

➊待机动画不能正常循环
设置开启待机动画-Idel，每次播放完毕后画面都会瞬间倒放到第一帧画面，再开始下一次的播放，不是无缝衔接的循环播放
※数据文件xxx.motion3.json的Loop和xxx.model3.json的FileLoop设为true或false，实际运行中并不生效

➋控制器Controllers的API
如最后一张图➋红框的MouseTracking、AutoBreath，ExtraMotion怎么进行开关呢？
※ 已知AutoBreath的关闭方式model.internalModel.breath = null;

<img width="447" alt="1" src="https://user-images.githubusercontent.com/111830324/204458872-8c5de2de-21a2-4bfa-aea8-7dd015efe90e.png">
<img width="443" alt="2" src="https://user-images.githubusercontent.com/111830324/204459157-c6ba28c5-3291-4953-9ecc-2a7a521c9540.png">

**Comment by guansss** [comment]
感谢支持~

> ➊待机动画不能正常循环

尝试一下设置过渡时间，比如：

```js
live2d.config.idleMotionFadingDuration = 500;
```

> ➋控制器Controllers的API

这里面的参数我一个都没见过……真的是官方软件导出的模型吗？还是从别的软件提取出来的，比如 Live2DViewerEX 之类

**Comment by Fpppps** [comment]
> > ➊待机动画不能正常循环
> 
> 尝试一下设置过渡时间，比如：
> 
> ```js
> import { config } from 'pixi-live2d-display';
> 
> config.idleMotionFadingDuration = 500;
> ```
没有解决哈，估计是有循环模式相关的参数设置，模型导入Live2DViewerEX是能正常使用


> > ➋控制器Controllers的API
> 
> 这里面的参数我一个都没见过……真的是官方软件导出的模型吗？还是从别的软件提取出来的，比如 Live2DViewerEX 之类

是官方软件导出的，设置过控制器的参数就会导出这些参数。Live2DViewerEX我都是导LPK格式到手机用的，在Live2DViewerEX是能正常使用。

**Comment by guansss** [comment]
设置后动作还是瞬间过渡吗？记得 config 要在创建模型之前设置，另外检查一下 motion3.json 里面是不是存在 `FadeInTime`/`FadeOutTime` 之类的参数覆盖掉了默认值

我查了一下，这些参数的确不是官方的，是 Live2DViewerEX 的自定义参数（https://live2d.pavostudio.com/doc/zh-cn/live2d/model-config/ ），最明显的就是这个 `IntimacySystem`，官方的功能里不可能有好感度系统

`Loop` 参数是官方的，但官方自己的 SDK 里面也没有实现，所以随缘吧，修不修复都有可能

**Comment by Fpppps** [comment]
好，明白了，非常感谢
最后想问一下鼠标追踪是可以用`model.internalModel.xxx = null`关闭掉的吗？
它的关键字是什么，我这边没找到

**Comment by guansss** [comment]
```js
const model = await Live2DModel.from('shizuku.model.json', { autoInteract: false });
```

https://guansss.github.io/pixi-live2d-display/interactions/#interacting-manually
