### ISSUE TITLE
请问支持点击触发motion动画的同时保持idle动画的播放吗？

### ISSUE THREAD

**Issue by Fpppps** [guansss/pixi-live2d-display#85]
如题，如果不支持的话，未来有计划补充这个功能吗？

PS：现在用户对于交互的丰富性要求越来高，感觉这类多个动画同时播放的功能会越来越必要，非常希望作者可以优化或者补充这方面的功能

**Comment by guansss** [comment]
目前不支持同时播放多个动画，未来有计划支持

**Comment by Fpppps** [comment]
> 目前不支持同时播放多个动画，未来有计划支持

好，感谢回复～
