### ISSUE TITLE
如何设置模型的Bounds

### ISSUE THREAD

**Issue by loclink** [guansss/pixi-live2d-display#93]
作者您好，请问如何在加载完模型之后更改模型的边界呢？

**Comment by guansss** [comment]
抱歉回复晚了

你说的是模型的边界还是 hit area 的边界？如果是模型边界的话，可以继承 Live2DModel 并重载 `Live2DModel.prototype._calculateBounds()`，如果是 hit area 的话，这个是通过顶点位置动态计算的，需要修改 `InternalModel.prototype.getDrawableBounds()`

**Comment by fishpigbird** [comment]
## 希望实现类似于ex studio中更改边界的效果，以修复鼠标追踪偏移。
![image](https://github.com/guansss/pixi-live2d-display/assets/128216091/1db03570-19b6-45d6-90fb-e9ad7eec700e)
## 我将代码更改后，鼠标追踪似乎仍然和以前一样有偏移，不清楚是否应该在这里更改，以自定义模型边界？
```
        _calculateBounds() {
            this._bounds.addFrame(this.transform, 0, -9000, this.internalModel.width, this.internalModel.height);
        }
```

```
       _calculateBounds() {
            this._bounds.addFrame(this.transform, 0, -this.internalModel.height/2, this.internalModel.width, this.internalModel.height);
        }
```
![image](https://github.com/guansss/pixi-live2d-display/assets/128216091/ea20f5af-8b70-4eae-a79b-f76e7513fa41)
