### ISSUE TITLE
求教如何录制并导出live2d动画

### ISSUE THREAD

**Issue by Hidoshikun** [guansss/pixi-live2d-display#98]
如果问题太过小白请见谅，因为我没做过前端……

我给项目添加了websocket支持，可以通过服务端发送指令控制live2d形象的动作表情，想把生成的动画序列导出，但没找到好的方案。

我尝试使用HTML5的MediaRecord来录制canvas，但调用start函数后一直没有数据，不知道是哪里出了问题。

**Comment by guansss** [comment]
这个问题不属于该插件的范畴，我无法回答
如果你认为是插件的 bug，请提供最小复现以供测试

**Comment by xing0322** [comment]
这个是live2D模型制作那块的内容，跟插件没有关系了，你需要先下载相关软件，比如Live2D Cubism Editor，官网有免费的下载方式，然后可以搜索一下关于这块的教程，官方有给，各大视频平台也有不少。
